#!/usr/bin/env bash
# FizzBuzz - print 1 to 100, "Fizz" for multiples of 3,
# "Buzz" for multiples of 5, and "FizzBuzz" for multiples of 3 and 5
for i in {1..100}
do
	if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ];
	then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
