#!/usr/bin/env bash
# Read file and manipulate fields to generate story
FILE="/etc/passwd"

while IFS=":" read -r user pw uid gid uinfo homedir shell
do
	echo -n "The user $user is part of the $gid gang, "
	echo -n "lives in $homedir and rides $shell."
	echo -n " $uid's place is protected by the passcode $pw, "
	echo "more info about the user here: $uinfo"
done < "$FILE"
